Tweak profile for improved readability
swiftlang/.github pull request #1
Opened 2024-06-10 22:16 UTC by Sajjon

Alternative profile for SwiftLang, which at least for me, improves readability. 

The three items in the enumerated list start with verbs in bold, encouraging engagement and also makes it a bit more glanceable, at least for me. Might be completely subjective :) 

Changed from `"we are"` to `"we're"` to be more consistent with other phrasing like `"that’s"` and `"It's"`.

After:
<img width="1297" alt="Screenshot 2024-06-11 at 00 12 30" src="https://github.com/swiftlang/.github/assets/864410/b8978a93-431e-433c-a2b7-9da0bbffc9b3">

2024-06-30 08:31 UTC, Dominic310303 approved these changes

2024-09-09 15:35 UTC, Sajjon commented
Context:

I informed lots of repos that Github user "vivoxfold3" had suspicous activity:
1. has no sources (only forks)
2. no profile photo
3. no followers
4. no bio
5. forks ~10 crypto libs or repos used by crypto libs / wallets all *within the same hour*
6. makes trivial contributions and **tries to "falsify" a GPG signature** by writing "Signed off by"
7. ignores PR templates

The **exact same behaviour** was done by GH use `vivoxfold3` also last week, which responded using... hmm... interesting phrasing:

https://github.com/hoprnet/hoprnet/pull/6482#issuecomment-2333638612

> "Unreasonable accusations from persecuted delusional patients"

Whatever that means? Obvious bad translation service.

==================

The difference between you vivoxfold3 and me is that I:
1. Have many of SOURCE repos (not forks) with many stars
2. My Github User is over 10 years old
3. I have profile photo
4. I have 100 followers
5. I have a bio
6. I have many verified email addresses
7. I'm a Github PRO user
8. I do in fact work in the crypto industry, unlike you doing trivial PRs intro 10 different crypto libs...
9. My contributions fixing typos are non-trivial - often spent 1-3 hours per

2025-03-14 05:46 UTC, plunker2025 commented
Well all make it stringing

2025-03-14 05:47 UTC, plunker2025 requested changes
Im looking  at out of. control  remote

2025-03-17 12:23 UTC, closed without merging